### PR TITLE
Separate feedback from thumbs up/down

### PR DESCRIPTION
**Pull request by runnabro**
Changes:
* Add leave feedback link
* Remove leave feedback link behavior from thumbs down

Screenshot 2019-07-11 17 38 10
Screenshot 2019-07-11 17 43 27

### CODE REVIEW

**Comment by sleslie23** [comment]
Hey @runnabro ! Meeta asked that we keep the feedback plugin live on the No event. That will still allow users to provide feedback after their expression of discontent.

The Leave Feedback link will allow people to provide feedback without having to click No. (e.g. when PM/Support/etc want to leave feedback).

**Comment by mojavelinux** [comment]
Please don't include a package-lock.json update in a UI change (unless a dependency change is required). These updates should be separate so that they're easier to track.

**Comment by runnabro** [comment]
@sleslie23 @mojavelinux Done. Thanks!

**Comment by sleslie23** [comment]
Thanks @runnabro !!!

**Comment by sleslie23** [comment]
@mojavelinux Can you give this PR a final review?

**Comment by mojavelinux** [comment]
LGTM!

Just make sure if there is a scenario a tester should verify, make sure it's listed here: https://github.com/mulesoft/docs-site-antora/blob/master/test-plan.adoc#tests (see last entry...maybe it needs to be revised or another added)

**Comment by runnabro** [comment]
> LGTM!
> 
> Just make sure if there is a scenario a tester should verify, make sure it's listed here: https://github.com/mulesoft/docs-site-antora/blob/master/test-plan.adoc#tests (see last entry...maybe it needs to be revised or another added)

Thanks for the suggestion. I opened a PR for that here: https://github.com/mulesoft/docs-site-antora/pull/417

**Pull request merged**
