### PR TITLE
DOCS-5568 add external link styles

### PR DESCRIPTION
**Pull request by runnabro**
Adds external styles for external links via `[target=_blank]`. Tested in Chrome, FF, IE11, Edge, Safari, iOS Safari, and responsively.

Screenshot 2019-07-12 15 11 52

### CODE REVIEW

**Comment by sleslie23** [comment]
@mojavelinux Hey Dan! We have a request to make external links open in a new window for one of our products. We are telling writers to use the following syntax: 

`https://help.salesforce.com/articleView?id=community_designer_overview.htm&type=5[Community Builder, role=external, window=_blank]`

Are there any advantages/disadvantages using this vs the ^ syntax?

**Comment by mojavelinux** [comment]
The `^` is simply a shorthand. If you prefer it, you can use it. If you like the longhand, that's fine too. It's what makes you the most comfortable.

The nice part about the '^' syntax is that it's a bit more abstract, so there isn't a hard reference to _blank as the name of the window. That could be useful down the road...or maybe not.

**Comment by mojavelinux** [comment]
It seems like it would be more maintainable if the SVG where stored as a separate file.

Regardless, we should use a consistent strategy. Sometimes we're embedding. Other times we're linking. I think we need to decide on the approach and stick with it.

(And we could always reconfigure the UI build to inline the SVG as base64 as an optimization, which gives us the best of both worlds, hence why storing the SVG in the source is a stronger option).

**Comment by runnabro** [comment]
@mojavelinux Thanks for the feedback; updated. Did I reference the image path correctly?

**Comment by mojavelinux** [comment]
The image path should begin with `../img` (relative starting from the location of the compiled stylesheet). If you use an absolute path, then it won't work in local mode (i.e., `file://` protocol).

**Comment by runnabro** [comment]
Fixed! Thanks a ton Dan.

**Pull request merged**
